### ISSUE TITLE
some photo will loss data 

### ISSUE THREAD

**Issue by zhiweny1122** [zjkhahah/HivisionIDPhotos-cpp#3]
Ubuntu22 : 
opencv4.10
Mnn 2.9
![1 pngresult_kb](https://github.com/user-attachments/assets/b6c74ab6-1b72-4d93-a0c6-1689d06aea90)

./HivisionIDPhotos_cpp -i demo/images/man2.jpg -o ./1.png   -r 255 -g 0 -b 0
![man2](https://github.com/user-attachments/assets/148bf40c-3d51-44a1-9ebd-48d87f21d860)

我是用的release里的HivisionIDPhotos-cpp-file.tar.gz and HivisionIDPhotos-cpp-1.1.zip .

**Comment by zjkhahah** [comment]
是蓝底正常 红底出现问题吗？

**Comment by zjkhahah** [comment]
更新了厂库 新增了输入参数 head_measure_ratio 你可以通过调整head_measure_ratio来适应你的需求
