### ISSUE TITLE
windows x64 mnn 2.9 opencv 4.7.0 编译出错

### ISSUE THREAD

**Issue by dog2code** [zjkhahah/HivisionIDPhotos-cpp#4]
如题，使用VS2022编译出错，使用ninja也一样出错。

看了一下有许多，其中比如"memcpy": function does not take 2 arguments

这应该不是mnn和opencv库没有链接正确的结果而是函数本身的问题，是因为VS版本不对吗？

此外，最新的 release没有head ratio这个输入参数，是否这个release并非源码编译的？

谢谢

**Comment by zjkhahah** [comment]
release 是之前版本的测试代码还没有加入最新编译 另外由于CMakeLists并没有屏蔽警告信息会出现一些关于内存的警告信息。这是正常的。如果出现报错可以发出截图，以进一步分析问题

**Comment by dog2code** [comment]
谢谢。所以我下载了源码想自己编译看看，如果有需要可以自己改，只不过没成功。我用Ninja和VS2022都尝试编译都失败，其中的确有很多警告信息，那个其实可以忽略，但是的确有很多错误，复制粘贴如下：

D:\HivisionIDPhotos-cpp-1.1\build>ninja
[1/6] Building CXX object CMakeFiles\HivisionIDphotos.dir\src\human_matting.cpp.obj
FAILED: CMakeFiles/HivisionIDphotos.dir/src/human_matting.cpp.obj
C:\PROGRA~2\MICROS~4\2022\BUILDT~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x64\cl.exe  /nologo /TP  -ID:\HivisionIDPhotos-cpp-1.1\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /wd4267 /wd4018 /wd4251 /wd4996 /wd4244 /wd4146 /wd4129 /wd4305 /wd4275 /wd4101 /MD /O2 /Ob2 /DNDEBUG /MT /Zi /showIncludes /FoCMakeFiles\HivisionIDphotos.dir\src\human_matting.cpp.obj /FdCMakeFiles\HivisionIDphotos.dir\ /FS -c D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp
cl : Command line warning D9025 : overriding '/MD' with '/MT'
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
D:\HivisionIDPhotos-cpp-1.1\include\opencv2/objdetect/aruco_board.hpp(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
D:\HivisionIDPhotos-cpp-1.1\include\cmdline.h(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(64): error C2065: 'channels': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(102): error C2065: 'bpp': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(103): error C2065: 'size_h': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(105): error C2065: 'bpp': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(106): error C2065: 'bpp': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(107): error C2065: 'size_h': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(108): error C2065: 'size_h': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(113): error C2065: 'bpp': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(113): error C2065: 'size_h': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(117): error C2065: 'size_h': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(117): error C2065: 'bpp': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(119): error C2065: 'size_h': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(136): error C2065: 'size_h': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(136): error C2660: 'memcpy': function does not take 2 arguments
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\vcruntime_string.h(43): note: see declaration of 'memcpy'
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(136): note: while trying to match the argument list '(T *, void *)'
        with
        [
            T=float
        ]
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(151): error C2065: 'size_h': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(152): error C2065: 'size_h': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(152): error C2660: 'memcpy': function does not take 2 arguments
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\vcruntime_string.h(43): note: see declaration of 'memcpy'
D:\HivisionIDPhotos-cpp-1.1\src\human_matting.cpp(152): note: while trying to match the argument list '(void *, T *)'
        with
        [
            T=float
        ]
[2/6] Building CXX object CMakeFiles\HivisionIDphotos.dir\src\image_adjustment.cpp.obj
FAILED: CMakeFiles/HivisionIDphotos.dir/src/image_adjustment.cpp.obj
C:\PROGRA~2\MICROS~4\2022\BUILDT~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x64\cl.exe  /nologo /TP  -ID:\HivisionIDPhotos-cpp-1.1\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /wd4267 /wd4018 /wd4251 /wd4996 /wd4244 /wd4146 /wd4129 /wd4305 /wd4275 /wd4101 /MD /O2 /Ob2 /DNDEBUG /MT /Zi /showIncludes /FoCMakeFiles\HivisionIDphotos.dir\src\image_adjustment.cpp.obj /FdCMakeFiles\HivisionIDphotos.dir\ /FS -c D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp
cl : Command line warning D9025 : overriding '/MD' with '/MT'
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
D:\HivisionIDPhotos-cpp-1.1\include\opencv2/objdetect/aruco_board.hpp(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
D:\HivisionIDPhotos-cpp-1.1\include\cmdline.h(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(77): error C2001: newline in constant
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(78): error C2143: syntax error: missing ')' before '}'
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(78): error C2143: syntax error: missing ';' before '}'
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(81): error C2065: 'correction': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(81): error C3079: an initializer list cannot be used as the right operand of this assignment operator
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(84): error C2065: 'correction': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(84): error C3079: an initializer list cannot be used as the right operand of this assignment operator
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(87): error C2065: 'correction': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(87): error C3079: an initializer list cannot be used as the right operand of this assignment operator
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(116): error C2065: 'correction': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(116): error C2065: 'correction': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(117): error C2065: 'correction': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(117): error C2065: 'correction': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(118): error C2065: 'correction': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(118): error C2065: 'correction': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(119): error C2065: 'correction': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\image_adjustment.cpp(119): error C2065: 'correction': undeclared identifier
[3/6] Building CXX object CMakeFiles\HivisionIDphotos.dir\src\tool.cpp.obj
FAILED: CMakeFiles/HivisionIDphotos.dir/src/tool.cpp.obj
C:\PROGRA~2\MICROS~4\2022\BUILDT~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x64\cl.exe  /nologo /TP  -ID:\HivisionIDPhotos-cpp-1.1\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /wd4267 /wd4018 /wd4251 /wd4996 /wd4244 /wd4146 /wd4129 /wd4305 /wd4275 /wd4101 /MD /O2 /Ob2 /DNDEBUG /MT /Zi /showIncludes /FoCMakeFiles\HivisionIDphotos.dir\src\tool.cpp.obj /FdCMakeFiles\HivisionIDphotos.dir\ /FS -c D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp
cl : Command line warning D9025 : overriding '/MD' with '/MT'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
D:\HivisionIDPhotos-cpp-1.1\include\opencv2/objdetect/aruco_board.hpp(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
D:\HivisionIDPhotos-cpp-1.1\include\cmdline.h(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(60): error C2065: 'i': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(60): error C2065: 'i': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(63): error C2065: 'layout_row_no_transpose': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(63): error C2065: 'i': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(66): error C2043: illegal break
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(69): error C2059: syntax error: 'for'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(69): error C2143: syntax error: missing ')' before ';'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(69): error C2143: syntax error: missing ';' before '<'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(69): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(69): error C2059: syntax error: '<'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(69): error C2059: syntax error: '++'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(69): error C2059: syntax error: ')'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(69): error C2143: syntax error: missing ';' before '{'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(69): error C2447: '{': missing function header (old-style formal list?)
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(79): error C2065: 'layout_row_no_transpose': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(79): error C2065: 'layout_col_no_transpose': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(82): error C2065: 'input_width': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(82): error C2065: 'i': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(82): error C2065: 'PHOTO_INTERVAL_H': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(82): error C2065: 'i': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(83): error C2059: syntax error: 'if'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(83): error C2143: syntax error: missing ';' before '{'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(83): error C2447: '{': missing function header (old-style formal list?)
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(87): error C2059: syntax error: 'else'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(87): error C2143: syntax error: missing ';' before '{'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(87): error C2447: '{': missing function header (old-style formal list?)
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(90): error C2059: syntax error: '}'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(90): error C2143: syntax error: missing ';' before '}'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(91): error C2143: syntax error: missing ')' before ';'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(91): error C2143: syntax error: missing ';' before '<'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(91): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(91): error C2086: 'int j': redefinition
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(69): note: see declaration of 'j'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(91): error C2059: syntax error: '<'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(91): error C2059: syntax error: '++'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(91): error C2059: syntax error: ')'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(92): error C2143: syntax error: missing ';' before '{'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(92): error C2447: '{': missing function header (old-style formal list?)
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(101): error C2065: 'layout_row_transpose': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(101): error C2065: 'layout_col_transpose': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(104): error C2059: syntax error: 'if'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(104): error C2143: syntax error: missing ';' before '{'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(104): error C2447: '{': missing function header (old-style formal list?)
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(107): error C2059: syntax error: 'else'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(107): error C2143: syntax error: missing ';' before '{'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(107): error C2447: '{': missing function header (old-style formal list?)
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(110): error C2059: syntax error: '}'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(110): error C2143: syntax error: missing ';' before '}'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(115): error C2143: syntax error: missing ';' before '{'
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(115): error C2447: '{': missing function header (old-style formal list?)
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(187): error C2065: 'roi': undeclared identifier
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(187): error C3861: 'white_background': identifier not found
D:\HivisionIDPhotos-cpp-1.1\src\tool.cpp(194): error C2065: 'white_background': undeclared identifier
[4/6] Building CXX object CMakeFiles\HivisionIDphotos.dir\src\MNN_LFFD.cpp.obj
cl : Command line warning D9025 : overriding '/MD' with '/MT'
D:\HivisionIDPhotos-cpp-1.1\include\opencv2/objdetect/aruco_board.hpp(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
D:\HivisionIDPhotos-cpp-1.1\include\cmdline.h(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
[5/6] Building CXX object CMakeFiles\HivisionIDphotos.dir\main.cpp.obj
cl : Command line warning D9025 : overriding '/MD' with '/MT'
D:\HivisionIDPhotos-cpp-1.1\include\opencv2/objdetect/aruco_board.hpp(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
D:\HivisionIDPhotos-cpp-1.1\include\cmdline.h(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
ninja: build stopped: subcommand failed.

顺便提一下，Lib文件夹下面我放了自己编译出来的mnn和opencv，是静态库但不是.a结尾而是.lib，我的环境是windows。
文件如下：

MNN.lib
opencv_calib3d470d.lib
opencv_core470d.lib
opencv_dnn470d.lib
opencv_features2d470d.lib
opencv_flann470d.lib
opencv_gapi470d.lib
opencv_highgui470d.lib
opencv_imgcodecs470d.lib
opencv_imgproc470d.lib
opencv_ml470d.lib
opencv_objdetect470d.lib
opencv_photo470d.lib
opencv_stitching470d.lib
opencv_video470d.lib
opencv_videoio470d.lib

**Comment by zjkhahah** [comment]
从提示信息看，你没有拉取仓库最新代码。建议拉取仓库更新后的代码再试一下，

**Comment by dog2code** [comment]
好的。之前的是我下载最新zip打包，这次我直接git clone https://github.com/zjkhahah/HivisionIDPhotos-cpp了
使用cmake一路默认生成配置文件后用vs2022打开，build这个项目后的确有了变化，只有三个error（warning有很多但是如你所说直接忽略了），如下：

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2001	newline in constant	HivisionIDphotos	D:\HivisionIDPhotos-cpp-master\HivisionIDPhotos-cpp\src\image_adjustment.cpp	72	
Error	C2143	syntax error: missing ')' before '}'	HivisionIDphotos	D:\HivisionIDPhotos-cpp-master\HivisionIDPhotos-cpp\src\image_adjustment.cpp	73	
Error	C2143	syntax error: missing ';' before '}'	HivisionIDphotos	D:\HivisionIDPhotos-cpp-master\HivisionIDPhotos-cpp\src\image_adjustment.cpp	73	

定位到对应代码：
...
std::vector<int> getBox(const cv::Mat& image, int model = 1, int correctionFactor = 0, int thresh = 127) {
    // 输入必须为四通道
    if (image.channels() != 4) {
        throw std::invalid_argument("输入的图像必须为四通道！");
    }
    // correc   tion_factor 规范化
...

经过测试发现，这里"输入的图像必须为四通道！"的中文提示出了问题，如果换成英文例如"Image must be in 4 channels!"，编译就通过成功了。。。

但是。。。

如果执行生成的exe文件，会跳出

"the code execution cannot proceed because opencv_imgcodes470.dll was not found. Reinstalling the program may fix this problem"，以及一系列动态链接库DLL找不到的出错。我一个一个把mnn.dll以及opencv若干dll复制到运行文件夹后，可以运行了，写在代码里的Demo图片文件提示找不到，我也复制过来，最后可以运行了。也生成了输出的测试文件，但是仍旧生成如下错误：

D:\HivisionIDPhotos-cpp-master\HivisionIDPhotos-cpp\runtime>HivisionIDphotos.exe
The device supports: i8sdot:0, fp16:0, i8mm: 0, sve2: 0
[ INFO:0@0.419] global registry_parallel.impl.hpp:96 cv::parallel::ParallelBackendRegistry::ParallelBackendRegistry core(parallel): Enabled backends(3, sorted by priority): ONETBB(1000); TBB(990); OPENMP(980)
[ INFO:0@0.420] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load D:\HivisionIDPhotos-cpp-master\HivisionIDPhotos-cpp\runtime\opencv_core_parallel_onetbb470_64d.dll => FAILED
[ INFO:0@0.421] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_onetbb470_64d.dll => FAILED
[ INFO:0@0.421] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load D:\HivisionIDPhotos-cpp-master\HivisionIDPhotos-cpp\runtime\opencv_core_parallel_tbb470_64d.dll => FAILED
[ INFO:0@0.422] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_tbb470_64d.dll => FAILED
[ INFO:0@0.422] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load D:\HivisionIDPhotos-cpp-master\HivisionIDPhotos-cpp\runtime\opencv_core_parallel_openmp470_64d.dll => FAILED
[ INFO:0@0.423] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_openmp470_64d.dll => FAILED
 浜哄儚鍒嗗壊妯″瀷鍔犺浇鍔犳帹鐞嗚€楁椂 1321ms.
 c++浜鸿劯妫€娴嬭€楁椂 328ms.
type=24 colos=4
h=413,(input_image.rows=413
x=75,y=162,wi=295,he=413
x=400,y=162,wi=295,he=413
x=725,y=162,wi=295,he=413
x=1050,y=162,wi=295,he=413
x=1375,y=162,wi=295,he=413
x=75,y=605,wi=295,he=413
x=400,y=605,wi=295,he=413
x=725,y=605,wi=295,he=413
x=1050,y=605,wi=295,he=413
x=1375,y=605,wi=295,he=413
 c++鍥惧儚鍚庡鐞嗚€楁椂 119ms.
 c++椤圭洰鑰楁椂 1842ms.

**Comment by zjkhahah** [comment]
感谢指出问题。应该是你的opencv库编译的出现了问题 你可以在[下载](https://github.com/zjkhahah/HivisionIDPhotos-cpp/releases/tag/v1.1)windows编译好的MNN和opencv库放到lib文件夹下编译。

**Comment by dog2code** [comment]
刚才尝试从零开始，git clone下载源码，
然后把上面帖子下载的mnn以及opencv的三个库全放到lib里面
cmake配置以后打开vs2022编译，还是出错，但是后来发现了问题

只要把Debug改成Release就可以顺利编译出来了

估计我的mnn和opencv也是默认Debug编译出来的库。那这个问题就解决了。我继续调试有问题另外发issue。谢谢
