### ISSUE TITLE
版本1.1命令行 head_measure_ratio参数-e显示option value is invalid

### ISSUE THREAD

**Issue by dog2code** [zjkhahah/HivisionIDPhotos-cpp#5]
如题

main中 p.add<float>("head_measure_ratio", 'e', "head_measure_ratio", false, 0.35, cmdline::range(0, 1)); 对-e参数做出了限制

输入介于0和1之间的小数，哪怕输入默认的0.35也会报错

option value is invalid: --head_measure_ratio=0.4

**Comment by zjkhahah** [comment]
很抱歉，我的问题是我提交的代码的错误。并没有经过很好的测试 你可以这样修改
![image](https://github.com/user-attachments/assets/ab19edf2-a0e3-4236-8e16-a103785e3d44)

**Comment by dog2code** [comment]
我很愿意帮忙测试，没事的

但是这个修改貌似没用。。。因为现在的问题是我的确输入了介于0和1之间的小数，他仍旧说我invalid。。。

**Comment by zjkhahah** [comment]
主仓库已经更新重新pull一下

**Comment by dog2code** [comment]
去掉了cmdline::range()后现在好了
